const projects = [
  {
    id: 1,
    title: "Whatsapp Clone",
    slug: "whatsapp-clone",
    isInEvidence: false,
    cardImage: "whatsapp-card.png",
    showImage: "whatsapp-show.png",
    description:
      "Replica del layout di Whatsapp resa responsive tramite Bootstrap. Nella webapp è possibile ricercare i contatti per nome, inviare messaggi e ricevere una risposta automatica, le funzionalità sono state implementate con VueJS.",
    liveLink: null,
    githubLink: "https://github.com/manuelloverso/vue-boolzapp",
    frontendLink: null,
    backendLink: null,
    youtubeLink: null,
    date: "2024-03-23",
    technologies: [
      "HTML",
      "CSS",
      "JavaScript",
      "VueJS",
      "Bootstrap",
      "Responsive",
    ],
  },
  {
    id: 2,
    title: "Netflix Clone",
    slug: "netflix-clone",
    isInEvidence: false,
    cardImage: "netflix-card.png",
    showImage: "netflix-show.png",
    description:
      "Replica del layout di Netflix. Con Vue e con l'utilizzo di un'API pubblica è possibile ricercare film e serie tv per nome, filtrare la ricerca per genere e visualizzare le informazioni relative al singolo titolo.",
    liveLink: null,
    githubLink: "https://github.com/manuelloverso/vite-boolflix",
    frontendLink: null,
    backendLink: null,
    youtubeLink: null,
    date: "2024-04-05",
    technologies: ["HTML", "CSS", "JavaScript", "VueJS", "APIs"],
  },
  {
    id: 3,
    title: "Portfolio Back-Office",
    slug: "portfolio-back-office",
    isInEvidence: true,
    cardImage: "portfolio-backoffice-card.png",
    showImage: "portfolio-backoffice-show.png",
    description:
      "In Laravel ho sviluppato un gestionale per questo sito, tramite il quale l'admin (in questo caso io), dopo essersi registrato, inserisce e rimuove progetti , tipologie e tecnologie utilizzate. Frontend e backend comunicano tramite delle chiamate axios.",
    liveLink: null,
    githubLink: "https://github.com/manuelloverso/backend-portfolio",
    frontendLink: null,
    backendLink: null,
    youtubeLink: null,
    date: "2024-05-29",
    technologies: [
      "HTML",
      "CSS",
      "Laravel",
      "Bootstrap",
      "Database",
      "PHP",
      "SQL",
    ],
  },
  {
    id: 4,
    title: "Deliveroo Clone",
    slug: "deliveroo-clone",
    isInEvidence: true,
    cardImage: "deliveroo-card.png",
    showImage: "deliveroo-show.png",
    description:
      "In team abbiamo replicato le funzionalità di Deliveroo. Il sito comprende una sezione back-office riservata all'utente registrato (ristoratore), sviluppata in Laravel, dove abbiamo implementato funzionalità come la gestione dei menù, la visualizzazione degli ordini ricevuti e l'analisi dell evendite tramite grafici mensili. La parte front pubblica, sviluppata in Vue, permette agli utenti non registrati di cercare ristoranti filtrandoli per categoria, visualizzare il menù del ristorante, aggiornare il carrello e inviare l'ordine dopo aver effettuato il pagamento. La ricerca dei ristoranti, l'invio degli ordini e l'accettazione dei pagamenti avvengono tramite chiamate axios, che permettono la comunicazione tra back-end e front-end.",
    liveLink: null,
    githubLink: null,
    frontendLink: "https://github.com/manuelloverso/deliveboo-vue",
    backendLink: "https://github.com/manuelloverso/DeliveBoo-laravel",
    youtubeLink: null,
    date: "2024-06-19",
    technologies: [
      "HTML",
      "CSS",
      "Laravel",
      "Bootstrap",
      "Database",
      "PHP",
      "SQL",
      "JavaScript",
      "VueJS",
      "Sass",
      "Responsive",
    ],
  },
  {
    id: 5,
    title: "Have you watched it?",
    slug: "have-you-watched-it",
    isInEvidence: true,
    cardImage: "hywi-card.png",
    showImage: "hywi-show.png",
    description:
      "Il mio primo progetto con React è una web app che permette agli utenti di cercare film tramite una barra di ricerca. Una volta selezionato un film, è possibile visualizzare dettagli come trama, genere, durata e altro. Gli utenti possono votare i film e aggiungerli alla propria lista di film visti, che viene salvata e rimane disponibile anche dopo il refresh della pagina, grazie all'uso del local storage.",
    liveLink: "https://haveyouwatchedit.netlify.app/",
    githubLink: "https://github.com/manuelloverso/react-movies-search",
    frontendLink: null,
    backendLink: null,
    youtubeLink: null,
    date: "2024-10-02",
    technologies: [
      "HTML",
      "CSS",
      "JavaScript",
      "React",
      "Tailwind CSS",
      "APIs",
      "Responsive",
    ],
  },
];

projects.reverse();

export default projects;
